# Generated by Django 2.2.1 on 2019-05-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
                ('position', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('resume', models.CharField(max_length=32)),
            ],
            bases=('user.user',),
        ),
    ]
