# Generated by Django 2.2.1 on 2019-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('ananymous', models.BooleanField(default=False)),
                ('interview_experience', models.CharField(max_length=10000)),
                ('like_dislike_counter', models.IntegerField()),
                ('hr_request', models.BooleanField(default=False)),
                ('comp_name', models.CharField(max_length=64)),
            ],
        ),
    ]
