# Generated by Django 2.2.1 on 2019-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('advertising_date', models.CharField(max_length=32)),
                ('closing_date', models.CharField(max_length=32)),
            ],
        ),
    ]
