# Generated by Django 2.2.1 on 2019-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('user_type', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('apartment_no', models.IntegerField()),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('e_mail', models.CharField(max_length=128)),
            ],
        ),
    ]
